-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNwDn3d5cRuv/Sa6/
g0yrSnxyfwgRuTAUHuAegvh67v+gCgYIKoZIzj0DAQehRANCAARWXzz4vB/Rf79G
cxlRkhZW0BMBG1Il5bfLENRKm2PZD/2ja4mjve0kkRAxBgyOixI8upyPOrHbVVXG
8FDFLrRi
-----END PRIVATE KEY-----